### ISSUE TITLE
Dollar sign escaping gone awry

### ISSUE THREAD

**Issue by jeremiahpslewis** [TuringLang/turing.ml#10]
Can't put my finger on the line of code, but think the issue in on the Turing.ml repo end, see:

https://turing.ml/dev/tutorials/2-logisticregression/

<img width="966" alt="Screen Shot 2021-03-14 at 19 31 07" src="https://user-images.githubusercontent.com/4462211/111079796-d6c7ad00-84fb-11eb-9f06-696a62c3149a.png">

**Comment by cpfiffer** [comment]
This may or not already be fixed, we haven't actually launched all the great stuff @torfjelde did recently moving us over to a much more streamlined process (`jmd-staging` is the relevant branch) . I think this should fix it.

**Comment by yebai** [comment]
@cpfiffer is this fixed now?

**Comment by jeremiahpslewis** [comment]
Yup

<img width="745" alt="Screen Shot 2022-01-26 at 22 56 44" src="https://user-images.githubusercontent.com/4462211/151253712-86cd7b87-dec9-4329-b54d-c2b20b7c8ac9.png">
https://turing.ml/dev/tutorials/02-logistic-regression/
