### ISSUE TITLE
Search doesn't work

### ISSUE THREAD

**Issue by ForceBru** [TuringLang/turing.ml#12]
When I input anything into the "Search" field and press Enter, nothing happens:

![t-rec](https://user-images.githubusercontent.com/8695383/120899598-3b952e00-c639-11eb-9b07-a14211eabe2c.gif)

The GIF doesn't show this, but I'm hitting Enter multiple times after typing each word

------

- macOS Catalina
- Safari 14.1.1

**Comment by cpfiffer** [comment]
Fixed with d7d534315f49576c6add5f0feade50b30b2b42ee.
