### ISSUE TITLE
Documentation about variational inference is broken

### ISSUE THREAD

**Issue by ForceBru** [TuringLang/turing.ml#19]
The "For developers -> Variational Inference" page (https://turing.ml/dev/docs/for-developers/variational_inference) looks like this for me:

![vi1](https://user-images.githubusercontent.com/8695383/126639691-1910413d-893d-458c-8339-ee9c9b1c1098.png)

![vi2](https://user-images.githubusercontent.com/8695383/126639739-cde910ac-6d2f-4d37-bcee-9c1cc82c19f7.png)

In words, the formatting is broken - some formulas are displayed as raw LaTeX and _all_ formulas that are correctly rendered are written out-of-line (in the middle of the text). For example, this is difficult to read:

![vi3](https://user-images.githubusercontent.com/8695383/126640067-7e3e9bbf-7428-4340-b1e5-850ee20f05c8.png)

-------

Furthermore, in the very beginning it says:

> Here we'll have a look at the theory behind VI, but if you're interested in how to use ADVI in Turing.jl, __checkout this tutorial__.

Where the `checkout this tutorial` link (https://turing.ml/dev/tutorials/9-variationalinference) says `404 File not found`. The same link appears at the bottom of the page:

> Now if you want to try it out, __check out the tutorial on how to use ADVI in Turing.jl__!

It also leads to the same non existing page.

Looks like the proper link is https://turing.ml/dev/tutorials/09-variational-inference/

**Comment by Alanocallaghan** [comment]
There's some broken mathjax in the current VI tutorial also, and I can't figure out where the MD is to edit it. The edit links point to the main Turing repo, and although this seems the current home, I can't find it here. https://turing.ml/dev/tutorials/09-variational-inference/

**Comment by yebai** [comment]
@torfjelde can you take a look this issue, and see whether we can fix the VI doc?

**Comment by devmotion** [comment]
It seems https://github.com/TuringLang/Turing.jl/pull/1869 fixed the documentation: https://turing.ml/dev/docs/for-developers/variational_inference
