### ISSUE TITLE
turing.ml blacklisted by Spamhaus

### ISSUE THREAD

**Issue by kmeers-kuleuven** [TuringLang/turing.ml#31]
Unfortunately we can not access the https://turing.ml documentation website because turing.ml is listed in the blacklist of [Spamhaus](https://check.spamhaus.org/listed/?searchterm=turing.ml).

Could you please try to get removed from the list?

**Comment by devmotion** [comment]
I just checked and turing.ml is not listed by Spamhaus: https://check.spamhaus.org/not_listed/?searchterm=turing.ml

Feel free to re-open the issue if the problem re-appears. Currently it seems to be fixed.
